CREATE TABLE IF NOT EXISTS attendance_disputes (
    dispute_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance_id BIGINT NOT NULL UNIQUE,
    submitted_image_path TEXT NOT NULL,
    master_image_path TEXT,
    reason TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    teacher_comment TEXT,
    reviewed_at TIMESTAMP,
    reviewed_by BIGINT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    CONSTRAINT fk_dispute_attendance
        FOREIGN KEY (attendance_id)
        REFERENCES attendance_records(attendance_id)
);
