spring.application.name=smart_attendance

# Server Configuration
#server.address=192.168.0.102
#server.address=localhost
server.port=8082
#server.port=8443
#server.ssl.enabled=true
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=changeit
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=localhost
app.dev.admin-id=1

server.forward-headers-strategy=framework

logging.level.com.smart_attendance=DEBUG

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_attendance
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

qr.secret=askbhdjhabsdukasbd
spring.profiles.active=dev
#spring.profiles.active=prod

